name: Test run

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    # Linux runner
    runs-on: ubuntu-latest
    # Container image that the job will run in
    container: python:3.10

    # Service containers
    services:
      redis:
        image: redis

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install requirements (ffmpeg)
        run: |
          apt-get update
          apt-get install -y ffmpeg
      - name: Test with pytest
        run: |
          pytest
